// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MisFinanzas.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MisFinanzas.Api.Data.Migrations
{
    [DbContext(typeof(FinanzasDbContext))]
    [Migration("20260929193834_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MisFinanzas.Api.Data.Budget", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.HasKey("UserId", "CategoryId")
                        .HasName("pk_budgets");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Category", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Grp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_grp", "grp IN ('fijos', 'variables', 'ahorros')");
                        });
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.IncomeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fuente");

                    b.Property<decimal>("M")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("m");

                    b.Property<string>("MonthK")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month_k");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_income_sources");

                    b.HasIndex("UserId", "MonthK")
                        .HasDatabaseName("ix_income_sources_user_id_month_k");

                    b.ToTable("income_sources", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.InvCategory", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_inv_categories");

                    b.ToTable("inv_categories", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.InvItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("concepto");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal?>("Gan")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("gan");

                    b.Property<string>("InvCategoryId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inv_category_id");

                    b.Property<decimal>("Monto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Pend")
                        .HasColumnType("boolean")
                        .HasColumnName("pend");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_inv_items");

                    b.HasIndex("UserId", "InvCategoryId")
                        .HasDatabaseName("ix_inv_items_user_id_inv_category_id");

                    b.ToTable("inv_items", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Loan", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("concepto");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kind");

                    b.Property<decimal>("Monto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean")
                        .HasColumnName("pagado");

                    b.Property<string>("Quien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quien");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_loans");

                    b.ToTable("loans", null, t =>
                        {
                            t.HasCheckConstraint("ck_loans_kind", "kind IN ('prestamo', 'deuda')");
                        });
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Month", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("K")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("k");

                    b.Property<decimal>("Ing")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("ing");

                    b.Property<bool>("Proj")
                        .HasColumnType("boolean")
                        .HasColumnName("proj");

                    b.Property<bool>("TieneIngresos")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_ingresos");

                    b.HasKey("UserId", "K")
                        .HasName("pk_months");

                    b.ToTable("months", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.SavingEntry", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nota");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("PotId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pot_id");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_saving_entries");

                    b.HasIndex("UserId", "PotId")
                        .HasDatabaseName("ix_saving_entries_user_id_pot_id");

                    b.ToTable("saving_entries", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.SavingPot", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_saving_pots");

                    b.ToTable("saving_pots", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Transaction", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_id");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("concepto");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("MonthK")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month_k");

                    b.Property<decimal>("Monto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("monto");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean")
                        .HasColumnName("pagado");

                    b.HasKey("UserId", "Id")
                        .HasName("pk_transactions");

                    b.HasIndex("UserId", "CategoryId")
                        .HasDatabaseName("ix_transactions_user_id_category_id");

                    b.HasIndex("UserId", "MonthK")
                        .HasDatabaseName("ix_transactions_user_id_month_k");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("Rev")
                        .HasColumnType("integer")
                        .HasColumnName("rev");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Budget", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.Category", null)
                        .WithOne("Budget")
                        .HasForeignKey("MisFinanzas.Api.Data.Budget", "UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_categories_user_id_category_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Category", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_users_user_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.IncomeSource", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.Month", null)
                        .WithMany("Ingresos")
                        .HasForeignKey("UserId", "MonthK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_income_sources_months_user_id_month_k");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.InvCategory", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inv_categories_users_user_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.InvItem", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.InvCategory", null)
                        .WithMany()
                        .HasForeignKey("UserId", "InvCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inv_items_inv_categories_user_id_inv_category_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Loan", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loans_users_user_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Month", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_months_users_user_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.SavingEntry", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.SavingPot", null)
                        .WithMany()
                        .HasForeignKey("UserId", "PotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saving_entries_saving_pots_user_id_pot_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.SavingPot", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saving_pots_users_user_id");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Transaction", b =>
                {
                    b.HasOne("MisFinanzas.Api.Data.Category", null)
                        .WithMany()
                        .HasForeignKey("UserId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_categories_user_id_category_id");

                    b.HasOne("MisFinanzas.Api.Data.Month", null)
                        .WithMany()
                        .HasForeignKey("UserId", "MonthK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_months_user_id_month_k");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Category", b =>
                {
                    b.Navigation("Budget");
                });

            modelBuilder.Entity("MisFinanzas.Api.Data.Month", b =>
                {
                    b.Navigation("Ingresos");
                });
#pragma warning restore 612, 618
        }
    }
}
